-----creacion de tablas de entidades-------------------

-----TABLA CLIENTE-------
CREATE TABLE CLIENTE(
IDCLIENTE NUMERIC(20),
NIT NUMERIC(20),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
DIRECCCION VARCHAR(100)
);

CREATE SEQUENCE SQC_CLIENTE
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_CLIENTE.NEXTVAL FROM DUAL


--TIPO COMBUSTIBLE-------
CREATE TABLE TIPO_COMBUSTIBLE(
ID_TIPO_COMBUSTIBLE NUMERIC(10),
COMBUSTIBLE VARCHAR(50)
);

CREATE SEQUENCE SQC_TIPO_COMBUSTIBLE
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_TIP0_COMBUSTIBLE.NEXTVAL FROM DUAL


---LUBRICANTES-----
CREATE TABLE LUBRINCANTE(
ID_LUBRINCANTE NUMERIC(20),
TIPO_ACEITE VARCHAR(50),
);

CREATE SEQUENCE SQC_LUBRICANTE
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_LUBRICANTE.NEXTVAL FROM DUAL

-----TABLA MARCA LUBRICANTES----
CREATE TABLE MARCA_LUBRICANTE(
ID_MARCA NUMERIC(50),
MARCA VARCHAR(50)
CONTENIDO VARCHAR(50)
);

CREATE SEQUENCE SQC_MARCA_LUBRICANTE
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_MARCA_LUBRICANTE.NEXTVAL FROM DUAL

-----TABLA TIPO VEHICULO----
CREATE TABLE TIPO_VEHICULO(
ID_VEHICULO NUMERIC(20),
VEHICULO VARCHAR(50)
);

CREATE SEQUENCE SQC_TIPO_VEHICULO
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_TIPO_VEHICULO.NEXTVAL FROM DUAL

---TABLA DEPARTMENTOS-----
CREATE TABLE DEPARTAMENTO_GUATEMALA(
ID_DEPARTAMENTO NUMERIC(50),
DEPARTAMETO VARCHAR(100)
);

CREATE SEQUENCE SQC_DEPARTAMENTO_GUATEMALA
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_DEPARTAMENTO_GUATEMALA.NEXTVAL FROM DUAL


-----TABLA MUNICIPIO----
CREATE TABLE MUNICIPIO_GUATEMALA(
ID_MUNICIPIO NUMERIC(50),
MUNICIPIO VARCHAR(100)
);

CREATE SEQUENCE SQC_MUNICIPIO_GUATEMALA
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_MUNICIPIO_GUATEMALA.NEXTVAL FROM DUAL


----TABLA CABECERAS DE GUATEMALA----
CREATE TABLE CABECERAS_GUATEMALA(
ID_CABECERA NUMERIC(50),
CABECERA VARCHAR(50)
);

CREATE SEQUENCE SQC_CABECERAS_GUATEMALA
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_CABECERAS_GUATEMALA.NEXTVAL FROM DUAL

----TABLA SEDES DE GASOLINERAS----
CREATE TABLE SEDE_ESTACION(
ID_SEDE NUMERIC(50)
SEDE VARCHAR(100)
);

CREATE SEQUENCE SQC_SEDE_ESTACION
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_SEDE_ESTACION.NEXTVAL FROM DUAL


---TABLA VEHICULOS----
CREATE TABLE VEHICULO(
ID_VEHICULO NUMERIC(50),
PLACA VARCHAR(50),
MARCA_VEHICULO VARCHAR(50),
COLOR_VEHICULO VARCHAR(50),
MODELO_VEHICULO NUMERIC(50)
);


----tabla FACTURA.-----
CREATE TABLE FACTURA(
IDFACTURA  NUMBER(10),
IDCLIENTE NUMBER(10),
FECHA DATE,
CONSTRAINT PK_UNIDAD PRIMARY KEY (IDFACTURA)
);

CREATE SEQUENCE SQC_FACTURA
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_FACTURAL.NEXTVAL FROM DUAL

CREATE TABLE DETALLE_FACTURA(
IDFACTURA  NUMBER(10),
IDCLIENTE NUMBER(10),
FECHA DATE,
CANTIDAD NUMBER(10,2),
PRECIO NUMBER(10,2),
CONSTRAINT PK_UNIDAD PRIMARY KEY (IDFACTURA)
);


CREATE SEQUENCE SQC_DETALLE_FACTURA
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_DETALLE_FACTURA.NEXTVAL FROM DUAL

CREATE TABLE MOV_INVENTARIO(
IDMOVIMIENTO NUMBER(18),
FECHAMOV DATE,
CODPROD NUMBER(10),
CANTIDAD NUMBER(10),
PRECIO NUMBER(10,2),
IDTIPOMOV NUMBER(10),
CONSTRAINT PK_MOVINV PRIMARY KEY (IDMOVIMIENTO)
);

CREATE SEQUENCE SQC_MOV_INVENTARIO
START WITH 1
MINVALUE 1
NOMAXVALUE
INCREMENT BY 1
CACHE 20;

SELECT SQC_MOV_INVENTARIO.NEXTVAL FROM DUAL


Select * From MOV_INVENTARIO;

--Script de Proyecto-----
------prueba ---script------

--Lester Marroquin
